# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180912_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu', to='app.StudentInfo'),
        ),
    ]
