# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180912_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='g',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu', to='app.Grade'),
        ),
    ]
