# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersTickets',
            new_name='UserTicket',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=220, unique=True, verbose_name='密码'),
        ),
    ]
