# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180917_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='icon',
            field=models.ImageField(null=True, upload_to='upload', verbose_name='头像'),
        ),
    ]
