# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180919_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('chang_myuser_username', '修改用户名'), ('change_myuser_password', '修改密码'))},
        ),
    ]
