# Generated by Django 2.0.7 on 2018-08-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0002_auto_20180801_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.AType'),
        ),
    ]
