# Generated by Django 2.0.7 on 2018-08-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0003_auto_20180801_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_recommend',
            field=models.BooleanField(default=False),
        ),
    ]
