# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=10, unique=True, verbose_name='班级名称')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=10, unique=True, verbose_name='姓名')),
                ('s_age', models.IntegerField(default=19, verbose_name='年龄')),
                ('s_sex', models.BooleanField(default=1, verbose_name='性别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('math', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('chinese', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('c', models.ManyToManyField(null=True, to='app4.Course')),
                ('g', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu', to='app4.Grade')),
            ],
            options={
                'db_table': 'app_student',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='地址')),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='stu_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu', to='app4.StudentInfo'),
        ),
    ]
